/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uwe.asGUI;

/**
 *
 * @author adw8
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form PractiseUI
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jColorChooser1 = new javax.swing.JColorChooser();
        jColorChooser2 = new javax.swing.JColorChooser();
        jOptionPane1 = new javax.swing.JOptionPane();
        jColorChooser3 = new javax.swing.JColorChooser();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        lgn_username_text = new javax.swing.JLabel();
        lgn_seperator = new javax.swing.JSeparator();
        lgn_password_text = new javax.swing.JLabel();
        lgn_password_field = new javax.swing.JPasswordField();
        lgn_seperator2 = new javax.swing.JSeparator();
        lgn_signIn_text = new java.awt.Label();
        lgn_username_textfield = new javax.swing.JTextField();
        lgn_signin_button = new javax.swing.JButton();
        lgn_icon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        lgn_username_text.setBackground(new java.awt.Color(255, 255, 255));
        lgn_username_text.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lgn_username_text.setForeground(new java.awt.Color(0, 0, 0));
        lgn_username_text.setText("Username");

        lgn_seperator.setBackground(new java.awt.Color(255, 0, 0));
        lgn_seperator.setForeground(new java.awt.Color(255, 0, 0));
        lgn_seperator.setToolTipText("");

        lgn_password_text.setBackground(new java.awt.Color(255, 255, 255));
        lgn_password_text.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lgn_password_text.setForeground(new java.awt.Color(0, 0, 0));
        lgn_password_text.setText("Password");

        lgn_password_field.setBackground(new java.awt.Color(255, 255, 255));
        lgn_password_field.setForeground(new java.awt.Color(0, 0, 0));
        lgn_password_field.setText("jPasswordField1");
        lgn_password_field.setBorder(null);

        lgn_seperator2.setBackground(new java.awt.Color(255, 0, 0));
        lgn_seperator2.setForeground(new java.awt.Color(255, 0, 0));

        lgn_signIn_text.setBackground(new java.awt.Color(255, 255, 255));
        lgn_signIn_text.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lgn_signIn_text.setForeground(new java.awt.Color(0, 0, 0));
        lgn_signIn_text.setText("Sign in");

        lgn_username_textfield.setBackground(new java.awt.Color(255, 255, 255));
        lgn_username_textfield.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lgn_username_textfield.setForeground(new java.awt.Color(0, 0, 0));
        lgn_username_textfield.setText("jTextField1");
        lgn_username_textfield.setBorder(null);
        lgn_username_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lgn_username_textfieldActionPerformed(evt);
            }
        });

        lgn_signin_button.setBackground(new java.awt.Color(255, 0, 0));
        lgn_signin_button.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lgn_signin_button.setForeground(new java.awt.Color(255, 255, 255));
        lgn_signin_button.setText("SIGN IN");
        lgn_signin_button.setBorder(null);
        lgn_signin_button.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lgn_signin_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lgn_signin_buttonActionPerformed(evt);
            }
        });

        lgn_icon.setIcon(new javax.swing.ImageIcon("C:\\Users\\adw8\\Downloads\\cityscape.png")); // NOI18N
        lgn_icon.setText("jLabel5");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(233, 233, 233)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lgn_username_text)
                    .addComponent(lgn_seperator, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lgn_password_text)
                    .addComponent(lgn_password_field, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lgn_seperator2, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lgn_signIn_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lgn_username_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lgn_signin_button, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lgn_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(229, 229, 229))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lgn_icon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(35, 35, 35)
                .addComponent(lgn_signIn_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lgn_username_text)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lgn_username_textfield)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lgn_seperator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lgn_password_text)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lgn_password_field, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lgn_seperator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lgn_signin_button, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lgn_signin_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lgn_signin_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lgn_signin_buttonActionPerformed

    private void lgn_username_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lgn_username_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lgn_username_textfieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JColorChooser jColorChooser2;
    private javax.swing.JColorChooser jColorChooser3;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lgn_icon;
    private javax.swing.JPasswordField lgn_password_field;
    private javax.swing.JLabel lgn_password_text;
    private javax.swing.JSeparator lgn_seperator;
    private javax.swing.JSeparator lgn_seperator2;
    private java.awt.Label lgn_signIn_text;
    private javax.swing.JButton lgn_signin_button;
    private javax.swing.JLabel lgn_username_text;
    private javax.swing.JTextField lgn_username_textfield;
    // End of variables declaration//GEN-END:variables
}
