package uwe.asGUI;

/**
 *
 * @author Adwait
 */
public class Login extends javax.swing.JFrame {

    public static uwe.as.Data_Cache data_cache;
    private Thread mainThread;

    public Login(Thread mainThread) {
        initComponents();
        this.mainThread = mainThread;
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialise the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jColorChooser1 = new javax.swing.JColorChooser();
        jColorChooser2 = new javax.swing.JColorChooser();
        jOptionPane1 = new javax.swing.JOptionPane();
        jColorChooser3 = new javax.swing.JColorChooser();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        label_username = new javax.swing.JLabel();
        label_password = new javax.swing.JLabel();
        textfield_password = new javax.swing.JPasswordField();
        label_signin = new java.awt.Label();
        textfield_username = new javax.swing.JTextField();
        button_signin = new javax.swing.JButton();
        label_Incorrect_Details = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(247, 245, 242));

        label_username.setBackground(new java.awt.Color(255, 255, 255));
        label_username.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        label_username.setText("Username");

        label_password.setBackground(new java.awt.Color(255, 255, 255));
        label_password.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        label_password.setText("Password");

        textfield_password.setBackground(new java.awt.Color(247, 245, 242));
        textfield_password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textfield_password.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        textfield_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfield_passwordActionPerformed(evt);
            }
        });

        label_signin.setBackground(new java.awt.Color(247, 245, 242));
        label_signin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label_signin.setForeground(new java.awt.Color(0, 0, 0));
        label_signin.setText("Sign in");

        textfield_username.setBackground(new java.awt.Color(247, 245, 242));
        textfield_username.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        textfield_username.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textfield_username.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        textfield_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfield_usernameActionPerformed(evt);
            }
        });

        button_signin.setBackground(new java.awt.Color(255, 0, 0));
        button_signin.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        button_signin.setForeground(new java.awt.Color(255, 255, 255));
        button_signin.setText("SIGN IN");
        button_signin.setBorder(null);
        button_signin.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        button_signin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_signinActionPerformed(evt);
            }
        });

        label_Incorrect_Details.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        label_Incorrect_Details.setText("Incorrect details, please try again.");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(233, 233, 233)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(label_password)
                    .addComponent(textfield_password, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_signin, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textfield_username, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(label_signin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(120, 120, 120))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(label_username))
                    .addComponent(label_Incorrect_Details))
                .addGap(229, 229, 229))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(label_signin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(label_username)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textfield_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(label_password)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textfield_password, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(button_signin, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(label_Incorrect_Details)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        label_Incorrect_Details.setVisible(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_signinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_signinActionPerformed
        String username = textfield_username.getText();
        char[] password = this.textfield_password.getPassword();
        
        uwe.as.User currentUser = data_cache.getUser(username.toUpperCase());
        
        if (currentUser != null)
        {
            System.out.println("User found!");
            if (data_cache.authenticate(currentUser, password)) {
                uwe.as.UWEAS.currentUser = currentUser;
                synchronized(mainThread)
                {
                    mainThread.notify();
                }
            }
            else
            {
                label_Incorrect_Details.setVisible(true);
            }
        }
        else
        {
            label_Incorrect_Details.setVisible(true);
        }
    }//GEN-LAST:event_button_signinActionPerformed

    private void textfield_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfield_usernameActionPerformed
        button_signin.doClick();
    }//GEN-LAST:event_textfield_usernameActionPerformed

    private void textfield_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfield_passwordActionPerformed
        button_signin.doClick();
    }//GEN-LAST:event_textfield_passwordActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_signin;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JColorChooser jColorChooser2;
    private javax.swing.JColorChooser jColorChooser3;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel label_Incorrect_Details;
    private javax.swing.JLabel label_password;
    private java.awt.Label label_signin;
    private javax.swing.JLabel label_username;
    private javax.swing.JPasswordField textfield_password;
    private javax.swing.JTextField textfield_username;
    // End of variables declaration//GEN-END:variables
}
