package uwe.asGUI;

import java.awt.Color;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import uwe.as.Hall;
import uwe.as.Lease;
import uwe.as.Room;
import uwe.as.User;

/**
 *
 * @author Adwait
 */
public class MainScreen extends javax.swing.JFrame {

    public static uwe.as.Data_Cache data_cache;
    private CreateLease createLease = null;

    /**
     * Creates new form MainScreen
     */
    public MainScreen() {
        initComponents();
        show_users_in_jtable();
        this.setVisible(true);
    }

    public void refresh_jtable() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        show_users_in_jtable();
    }

    public void show_users_in_jtable() {
        // Pulling data lists from cache
        List<Room> rooms = data_cache.getRooms();
        List<Lease> leases = data_cache.getLeases();
        List<Hall> halls = data_cache.getHalls();

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        Object[] row = new Object[9];

        if (halls != null && rooms != null && leases != null) {
            for (int j = 0; j < halls.size(); j++) {
                Hall currentHall = halls.get(j);
                //System.out.println(currentHall);

                for (int i = 0; i < rooms.size(); i++) {
                    Room currentRoom = rooms.get(i);

                    if (currentRoom.getHallUID() == currentHall.getUID()) {

                        for (Lease l : leases) {
                            
                            if(currentRoom.getLeases().contains(l.getUID())) {
                                User currentUser = data_cache.getUser(l.getStudentUID());

                                if (currentUser != null) {
                                    row[0] = l.getLeaseNumber();
                                    row[1] = currentHall.getName();
                                    row[2] = currentHall.getNumber();
                                    row[3] = currentRoom.getNumber();
                                    row[4] = currentUser.getName();
                                    row[5] = currentUser.getUID();
                                    row[6] = currentRoom.getCleaniness();
                                    row[7] = l.getUID();
                                    row[8] = currentRoom.getUID();
                                    model.addRow(row);
                                }

                            }
                            if (currentRoom.getLeases().isEmpty() || currentRoom.getLeases() == null) {
                                System.out.println(currentRoom.getLeases());
                                row[0] = "";
                                row[1] = currentHall.getName();
                                row[2] = currentHall.getNumber();
                                row[3] = currentRoom.getNumber();
                                row[4] = "";
                                row[5] = "";
                                row[6] = currentRoom.getCleaniness();
                                row[7] = "";
                                row[8] = currentRoom.getUID();
                                model.addRow(row);
                                break;
                            }

                        }

                    }

                }
            }
        }
    }
    
    public void createLeaseClosing()
    {
        this.createLease = null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ms_panel = new javax.swing.JPanel();
        ms_uwe_text = new javax.swing.JLabel();
        ms_seperator = new javax.swing.JSeparator();
        ms_btn_hallmanager = new javax.swing.JPanel();
        ms_ind_hallmanager = new javax.swing.JPanel();
        ms_hallmanager_text = new javax.swing.JLabel();
        ms_btn_warden = new javax.swing.JPanel();
        ms_ind_warden = new javax.swing.JPanel();
        ms_warden_text = new javax.swing.JLabel();
        ms_btn_all = new javax.swing.JPanel();
        ms_ind_all = new javax.swing.JPanel();
        ms_btn_all_text = new javax.swing.JLabel();
        ms_database_table = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        room_number_tf = new javax.swing.JTextField();
        hall_number_tf = new javax.swing.JTextField();
        hall_name_tf = new javax.swing.JTextField();
        lease_number_tf = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        student_name_tf = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        l_hall_number_tf = new javax.swing.JTextField();
        l_hall_name_tf = new javax.swing.JTextField();
        l_room_number_tf = new javax.swing.JTextField();
        l_lease_number_tf = new javax.swing.JTextField();
        l_student_name_tf = new javax.swing.JTextField();
        l_btn_delete = new javax.swing.JButton();
        buttonAddLease = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        l_student_uid_tf = new javax.swing.JTextField();
        l_hall_uid_tf = new javax.swing.JTextField();
        l_lease_uid_tf = new javax.swing.JTextField();
        l_room_uid_tf = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("UWE Accomodation App");
        setBackground(new java.awt.Color(247, 245, 242));
        setLocationByPlatform(true);

        ms_panel.setBackground(new java.awt.Color(247, 245, 242));

        ms_uwe_text.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ms_uwe_text.setText("UWE Accomodation");

        ms_seperator.setBackground(new java.awt.Color(247, 245, 242));

        ms_btn_hallmanager.setBackground(new java.awt.Color(247, 245, 242));
        ms_btn_hallmanager.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ms_btn_hallmanagerMousePressed(evt);
            }
        });

        ms_ind_hallmanager.setBackground(new java.awt.Color(19, 19, 19));
        ms_ind_hallmanager.setOpaque(false);

        javax.swing.GroupLayout ms_ind_hallmanagerLayout = new javax.swing.GroupLayout(ms_ind_hallmanager);
        ms_ind_hallmanager.setLayout(ms_ind_hallmanagerLayout);
        ms_ind_hallmanagerLayout.setHorizontalGroup(
            ms_ind_hallmanagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        ms_ind_hallmanagerLayout.setVerticalGroup(
            ms_ind_hallmanagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        ms_hallmanager_text.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ms_hallmanager_text.setText("Hall Manager");
        ms_hallmanager_text.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ms_hallmanager_textMousePressed(evt);
            }
        });

        javax.swing.GroupLayout ms_btn_hallmanagerLayout = new javax.swing.GroupLayout(ms_btn_hallmanager);
        ms_btn_hallmanager.setLayout(ms_btn_hallmanagerLayout);
        ms_btn_hallmanagerLayout.setHorizontalGroup(
            ms_btn_hallmanagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ms_btn_hallmanagerLayout.createSequentialGroup()
                .addComponent(ms_ind_hallmanager, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ms_hallmanager_text, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ms_btn_hallmanagerLayout.setVerticalGroup(
            ms_btn_hallmanagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ms_ind_hallmanager, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(ms_btn_hallmanagerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ms_hallmanager_text)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        ms_btn_warden.setBackground(new java.awt.Color(247, 245, 242));
        ms_btn_warden.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ms_btn_wardenMousePressed(evt);
            }
        });

        ms_ind_warden.setBackground(new java.awt.Color(19, 19, 19));
        ms_ind_warden.setOpaque(false);

        javax.swing.GroupLayout ms_ind_wardenLayout = new javax.swing.GroupLayout(ms_ind_warden);
        ms_ind_warden.setLayout(ms_ind_wardenLayout);
        ms_ind_wardenLayout.setHorizontalGroup(
            ms_ind_wardenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        ms_ind_wardenLayout.setVerticalGroup(
            ms_ind_wardenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        ms_warden_text.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ms_warden_text.setText("Warden");

        javax.swing.GroupLayout ms_btn_wardenLayout = new javax.swing.GroupLayout(ms_btn_warden);
        ms_btn_warden.setLayout(ms_btn_wardenLayout);
        ms_btn_wardenLayout.setHorizontalGroup(
            ms_btn_wardenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ms_btn_wardenLayout.createSequentialGroup()
                .addComponent(ms_ind_warden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ms_warden_text, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ms_btn_wardenLayout.setVerticalGroup(
            ms_btn_wardenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ms_ind_warden, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(ms_btn_wardenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ms_warden_text)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        ms_btn_all.setBackground(new java.awt.Color(247, 245, 242));
        ms_btn_all.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ms_btn_allMousePressed(evt);
            }
        });

        ms_ind_all.setBackground(new java.awt.Color(19, 19, 19));
        ms_ind_all.setOpaque(false);

        javax.swing.GroupLayout ms_ind_allLayout = new javax.swing.GroupLayout(ms_ind_all);
        ms_ind_all.setLayout(ms_ind_allLayout);
        ms_ind_allLayout.setHorizontalGroup(
            ms_ind_allLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        ms_ind_allLayout.setVerticalGroup(
            ms_ind_allLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        ms_btn_all_text.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ms_btn_all_text.setText("All");

        javax.swing.GroupLayout ms_btn_allLayout = new javax.swing.GroupLayout(ms_btn_all);
        ms_btn_all.setLayout(ms_btn_allLayout);
        ms_btn_allLayout.setHorizontalGroup(
            ms_btn_allLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ms_btn_allLayout.createSequentialGroup()
                .addComponent(ms_ind_all, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ms_btn_all_text, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ms_btn_allLayout.setVerticalGroup(
            ms_btn_allLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ms_ind_all, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(ms_btn_allLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ms_btn_all_text)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ms_panelLayout = new javax.swing.GroupLayout(ms_panel);
        ms_panel.setLayout(ms_panelLayout);
        ms_panelLayout.setHorizontalGroup(
            ms_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ms_panelLayout.createSequentialGroup()
                .addGroup(ms_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ms_panelLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(ms_uwe_text))
                    .addGroup(ms_panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ms_seperator, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(ms_btn_warden, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ms_btn_hallmanager, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ms_btn_all, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ms_panelLayout.setVerticalGroup(
            ms_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ms_panelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(ms_uwe_text)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ms_seperator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(ms_btn_hallmanager, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(ms_btn_warden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(ms_btn_all, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Lease Number", "Hall Name", "Hall Number ", "Room Number", "Student Name", "Student ID", "Cleaning Status", "Lease ID", "RoomID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        ms_database_table.setViewportView(jTable1);

        jPanel2.setBackground(new java.awt.Color(247, 245, 242));
        jPanel2.setLayout(new java.awt.CardLayout());

        jPanel3.setBackground(new java.awt.Color(247, 245, 242));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Room Cleaning Status");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Hall Name");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Hall Number");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Room Number");

        room_number_tf.setEditable(false);
        room_number_tf.setBackground(new java.awt.Color(247, 245, 242));
        room_number_tf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        hall_number_tf.setEditable(false);
        hall_number_tf.setBackground(new java.awt.Color(247, 245, 242));
        hall_number_tf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        hall_name_tf.setEditable(false);
        hall_name_tf.setBackground(new java.awt.Color(247, 245, 242));
        hall_name_tf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        hall_name_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hall_name_tfActionPerformed(evt);
            }
        });

        lease_number_tf.setEditable(false);
        lease_number_tf.setBackground(new java.awt.Color(247, 245, 242));
        lease_number_tf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("Lease Number");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("Student Name");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setText("Occupancy");

        student_name_tf.setBackground(new java.awt.Color(247, 245, 242));
        student_name_tf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jComboBox2.setBackground(new java.awt.Color(247, 245, 242));
        jComboBox2.setEditable(true);
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Clean", "Dirty", "Offline" }));
        jComboBox2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setText("Room Status");

        jComboBox3.setBackground(new java.awt.Color(247, 245, 242));
        jComboBox3.setEditable(true);
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Unoccupied", "Occupied" }));
        jComboBox3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton3.setText("Apply");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(26, 26, 26)
                        .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(36, 36, 36)
                .addComponent(jButton3)
                .addGap(166, 166, 166))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel10)
                        .addComponent(jLabel11)
                        .addComponent(jLabel12))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(room_number_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(hall_number_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(hall_name_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel13))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(36, 36, 36)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel15)
                                .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING))))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lease_number_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(student_name_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(10, Short.MAX_VALUE)))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(379, 379, 379)
                    .addComponent(jComboBox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(16, 16, 16)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 172, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addGap(7, 7, 7))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(51, 51, 51)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel10)
                                .addComponent(hall_name_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel13))
                            .addGap(35, 35, 35)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel11)
                                .addComponent(hall_number_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel14))
                            .addGap(38, 38, 38)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel12)
                                .addComponent(room_number_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel15)))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(lease_number_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(35, 35, 35)
                            .addComponent(student_name_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(58, Short.MAX_VALUE)))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addContainerGap(174, Short.MAX_VALUE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(42, 42, 42)))
        );

        jPanel2.add(jPanel3, "card2");

        jPanel4.setBackground(new java.awt.Color(247, 245, 242));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Admin All Access");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(370, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(211, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel4, "card2");

        jPanel1.setBackground(new java.awt.Color(247, 245, 242));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Lease Information");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Hall Number");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Hall Name");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Room Number");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Lease Number");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Student Name");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Occupancy");

        l_hall_number_tf.setBackground(new java.awt.Color(247, 245, 242));
        l_hall_number_tf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        l_hall_name_tf.setBackground(new java.awt.Color(247, 245, 242));
        l_hall_name_tf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        l_hall_name_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l_hall_name_tfActionPerformed(evt);
            }
        });

        l_room_number_tf.setBackground(new java.awt.Color(247, 245, 242));
        l_room_number_tf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        l_lease_number_tf.setBackground(new java.awt.Color(247, 245, 242));
        l_lease_number_tf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        l_student_name_tf.setBackground(new java.awt.Color(247, 245, 242));
        l_student_name_tf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        l_btn_delete.setText("Delete");
        l_btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l_btn_deleteActionPerformed(evt);
            }
        });

        buttonAddLease.setText("Add Lease");
        buttonAddLease.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddLeaseActionPerformed(evt);
            }
        });

        jComboBox1.setBackground(new java.awt.Color(247, 245, 242));
        jComboBox1.setEditable(true);
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Unoccupied", "Occupied" }));
        jComboBox1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        l_student_uid_tf.setText("jTextField1");

        l_hall_uid_tf.setText("jTextField1");

        l_lease_uid_tf.setText("jTextField2");

        l_room_uid_tf.setText("jTextField3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(l_room_number_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l_hall_number_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l_hall_name_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(l_lease_number_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(l_student_name_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(l_student_uid_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l_hall_uid_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l_lease_uid_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l_room_uid_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(l_btn_delete)
                        .addGap(37, 37, 37)
                        .addComponent(buttonAddLease)
                        .addGap(9, 9, 9)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(l_hall_name_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(l_hall_number_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(l_room_number_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(l_lease_number_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(l_student_name_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonAddLease)
                            .addComponent(l_btn_delete))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(l_student_uid_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(l_hall_uid_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(l_lease_uid_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(l_room_uid_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(12, Short.MAX_VALUE))))
        );

        jPanel2.add(jPanel1, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(ms_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ms_database_table))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(ms_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ms_database_table, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ms_hallmanager_textMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ms_hallmanager_textMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_ms_hallmanager_textMousePressed

    private void ms_btn_hallmanagerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ms_btn_hallmanagerMousePressed
        // TODO add your handling code here:
        setColor(ms_btn_hallmanager);
        resetColor(ms_btn_all);
        resetColor(ms_btn_warden);
        ms_ind_hallmanager.setOpaque(true);
        ms_ind_warden.setOpaque(false);
        ms_ind_all.setOpaque(false);

        jPanel1.setVisible(true);
        jPanel3.setVisible(false);
        jPanel4.setVisible(false);

    }//GEN-LAST:event_ms_btn_hallmanagerMousePressed

    private void ms_btn_wardenMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ms_btn_wardenMousePressed
        // TODO add your handling code here:
        setColor(ms_btn_warden);
        resetColor(ms_btn_all);
        resetColor(ms_btn_hallmanager);
        ms_ind_warden.setOpaque(true);
        ms_ind_hallmanager.setOpaque(false);
        ms_ind_all.setOpaque(false);

        jPanel1.setVisible(false);
        jPanel3.setVisible(true);
        jPanel4.setVisible(false);
    }//GEN-LAST:event_ms_btn_wardenMousePressed

    private void ms_btn_allMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ms_btn_allMousePressed
        // TODO add your handling code here:
        setColor(ms_btn_all);
        resetColor(ms_btn_hallmanager);
        resetColor(ms_btn_warden);
        ms_ind_hallmanager.setOpaque(false);
        ms_ind_warden.setOpaque(false);
        ms_ind_all.setOpaque(true);

        jPanel1.setVisible(false);
        jPanel3.setVisible(false);
        jPanel4.setVisible(true);
    }//GEN-LAST:event_ms_btn_allMousePressed

    private void l_hall_name_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l_hall_name_tfActionPerformed


    }//GEN-LAST:event_l_hall_name_tfActionPerformed

    private void l_btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l_btn_deleteActionPerformed
        // TODO add your handling code here:
        Lease lease = data_cache.getLease(Integer.parseInt(l_lease_uid_tf.getText()));
        Room room = data_cache.getRoom(Integer.parseInt(l_room_uid_tf.getText()));
        User user = data_cache.getUser(Integer.parseInt(l_student_uid_tf.getText()));

        if ((l_student_name_tf.getText() == null || l_student_name_tf.getText().trim().isEmpty()) && (l_lease_number_tf.getText() == null || l_lease_number_tf.getText().trim().isEmpty())) {
            JOptionPane.showMessageDialog(null, "Lease already deleted", "Inane warning", JOptionPane.WARNING_MESSAGE);
        } else if (room.getLeases().contains(lease.getUID())) {
            data_cache.removeLease(lease);
            refresh_jtable();
            
            
            
        }


    }//GEN-LAST:event_l_btn_deleteActionPerformed

    private void hall_name_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hall_name_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hall_name_tfActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void buttonAddLeaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddLeaseActionPerformed
        if (createLease == null)
        {
            CreateLease createLease = new CreateLease(this);
        }
    }//GEN-LAST:event_buttonAddLeaseActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int i = jTable1.getSelectedRow();
        TableModel model = jTable1.getModel();
        // Warden: Room cleaning info
        lease_number_tf.setText(model.getValueAt(i, 0).toString());
        hall_name_tf.setText(model.getValueAt(i, 1).toString());
        hall_number_tf.setText(model.getValueAt(i, 2).toString());
        room_number_tf.setText(model.getValueAt(i, 3).toString());
        student_name_tf.setText(model.getValueAt(i, 4).toString());

        //Hall manager: Lease information
        if (l_lease_number_tf.getText() == null){
            l_lease_number_tf.setText("");
            l_hall_name_tf.setText(model.getValueAt(i, 1).toString());
            l_hall_number_tf.setText(model.getValueAt(i, 2).toString());
            l_room_number_tf.setText(model.getValueAt(i, 3).toString());
            l_student_name_tf.setText(model.getValueAt(i, 4).toString());
            l_student_uid_tf.setText("");
            l_lease_uid_tf.setText("");
            l_room_uid_tf.setText(model.getValueAt(i, 8).toString());
        }else{        
        l_lease_number_tf.setText(model.getValueAt(i, 0).toString());
        l_hall_name_tf.setText(model.getValueAt(i, 1).toString());
        l_hall_number_tf.setText(model.getValueAt(i, 2).toString());
        l_room_number_tf.setText(model.getValueAt(i, 3).toString());
        l_student_name_tf.setText(model.getValueAt(i, 4).toString());
        l_student_uid_tf.setText(model.getValueAt(i, 5).toString());
        l_lease_uid_tf.setText(model.getValueAt(i, 7).toString());
        l_room_uid_tf.setText(model.getValueAt(i, 8).toString());
        }

    }//GEN-LAST:event_jTable1MouseClicked

    // loading smaple data
    void setColor(JPanel panel) {
        panel.setBackground(new Color(197, 196, 193));
    }

    void resetColor(JPanel panel) {
        panel.setBackground(new Color(247, 245, 242));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAddLease;
    private javax.swing.JTextField hall_name_tf;
    private javax.swing.JTextField hall_number_tf;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton l_btn_delete;
    private javax.swing.JTextField l_hall_name_tf;
    private javax.swing.JTextField l_hall_number_tf;
    private javax.swing.JTextField l_hall_uid_tf;
    private javax.swing.JTextField l_lease_number_tf;
    private javax.swing.JTextField l_lease_uid_tf;
    private javax.swing.JTextField l_room_number_tf;
    private javax.swing.JTextField l_room_uid_tf;
    private javax.swing.JTextField l_student_name_tf;
    private javax.swing.JTextField l_student_uid_tf;
    private javax.swing.JTextField lease_number_tf;
    private javax.swing.JPanel ms_btn_all;
    private javax.swing.JLabel ms_btn_all_text;
    private javax.swing.JPanel ms_btn_hallmanager;
    private javax.swing.JPanel ms_btn_warden;
    private javax.swing.JScrollPane ms_database_table;
    private javax.swing.JLabel ms_hallmanager_text;
    private javax.swing.JPanel ms_ind_all;
    private javax.swing.JPanel ms_ind_hallmanager;
    private javax.swing.JPanel ms_ind_warden;
    private javax.swing.JPanel ms_panel;
    private javax.swing.JSeparator ms_seperator;
    private javax.swing.JLabel ms_uwe_text;
    private javax.swing.JLabel ms_warden_text;
    private javax.swing.JTextField room_number_tf;
    private javax.swing.JTextField student_name_tf;
    // End of variables declaration//GEN-END:variables
}
