package uwe.asGUI;

/**
 *
 * @author Jamie Mills (16004255)
 */
public class ViewApplications extends javax.swing.JFrame {
    public static uwe.as.Data_Cache data_cache;
    /**
     * Creates new form CreateApplication
     */
    public ViewApplications() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_Hall = new javax.swing.JLabel();
        label_Room = new javax.swing.JLabel();
        label_StartDate = new javax.swing.JLabel();
        label_Duration = new javax.swing.JLabel();
        button_Apply = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textbox_RoomDesc = new javax.swing.JTextPane();
        label_Description = new javax.swing.JLabel();
        label_Price = new javax.swing.JLabel();
        textbox_Price = new javax.swing.JFormattedTextField();
        comboBox_CreateApplication_Hall = new javax.swing.JComboBox<>();
        comboBox_Room = new javax.swing.JComboBox<>();
        textbox_StartDate = new javax.swing.JFormattedTextField();
        textbox_Duration = new javax.swing.JFormattedTextField();
        button_Cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label_Hall.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        label_Hall.setText("Hall");

        label_Room.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        label_Room.setText("Room");

        label_StartDate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        label_StartDate.setText("Start Date");

        label_Duration.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        label_Duration.setText("Duration");

        button_Apply.setText("Apply");
        button_Apply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_ApplyActionPerformed(evt);
            }
        });

        textbox_RoomDesc.setEditable(false);
        jScrollPane1.setViewportView(textbox_RoomDesc);

        label_Description.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        label_Description.setText("Description");

        label_Price.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        label_Price.setText("Price (PCM)");

        textbox_Price.setEditable(false);
        textbox_Price.setMaximumSize(new java.awt.Dimension(100, 20));
        textbox_Price.setMinimumSize(new java.awt.Dimension(100, 20));
        textbox_Price.setPreferredSize(new java.awt.Dimension(100, 20));

        comboBox_CreateApplication_Hall.setMaximumSize(new java.awt.Dimension(100, 20));
        comboBox_CreateApplication_Hall.setMinimumSize(new java.awt.Dimension(100, 20));
        comboBox_CreateApplication_Hall.setPreferredSize(new java.awt.Dimension(100, 20));

        comboBox_Room.setMaximumSize(new java.awt.Dimension(100, 20));
        comboBox_Room.setMinimumSize(new java.awt.Dimension(100, 20));
        comboBox_Room.setPreferredSize(new java.awt.Dimension(100, 20));

        textbox_StartDate.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        textbox_StartDate.setMaximumSize(new java.awt.Dimension(100, 20));
        textbox_StartDate.setMinimumSize(new java.awt.Dimension(100, 20));
        textbox_StartDate.setPreferredSize(new java.awt.Dimension(100, 20));

        textbox_Duration.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        textbox_Duration.setMaximumSize(new java.awt.Dimension(100, 20));
        textbox_Duration.setMinimumSize(new java.awt.Dimension(100, 20));
        textbox_Duration.setPreferredSize(new java.awt.Dimension(100, 20));

        button_Cancel.setText("Cancel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label_Hall)
                                    .addComponent(label_Room))
                                .addGap(85, 85, 85)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(comboBox_CreateApplication_Hall, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(comboBox_Room, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(label_Description))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label_Duration)
                                    .addComponent(label_StartDate))
                                .addGap(28, 28, 28))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label_Price)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textbox_Price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textbox_StartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textbox_Duration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(72, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(button_Apply)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(button_Cancel)
                        .addGap(9, 9, 9))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_StartDate)
                    .addComponent(textbox_StartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBox_CreateApplication_Hall, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_Hall))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_Duration)
                    .addComponent(textbox_Duration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBox_Room, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_Room))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textbox_Price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_Price)
                    .addComponent(label_Description))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(button_Apply)
                            .addComponent(button_Cancel))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_ApplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_ApplyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button_ApplyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateApplication().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_Apply;
    private javax.swing.JButton button_Cancel;
    private javax.swing.JComboBox<String> comboBox_CreateApplication_Hall;
    private javax.swing.JComboBox<String> comboBox_Room;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_Description;
    private javax.swing.JLabel label_Duration;
    private javax.swing.JLabel label_Hall;
    private javax.swing.JLabel label_Price;
    private javax.swing.JLabel label_Room;
    private javax.swing.JLabel label_StartDate;
    private javax.swing.JFormattedTextField textbox_Duration;
    private javax.swing.JFormattedTextField textbox_Price;
    private javax.swing.JTextPane textbox_RoomDesc;
    private javax.swing.JFormattedTextField textbox_StartDate;
    // End of variables declaration//GEN-END:variables
}
